language: ruby
sudo: false
gemfile: nubis/travis/Gemfile
cache:
  bundler: true
  directories:
  - "${HOME}/bin"
  - nubis/librarian-puppet
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck
script:
- nubis/travis/run-checks
- ./run.sh
notifications:
  slack:
    secure: m0UqU6EjiDFKzGSvKlndym1mdB9XeDEYQa3pKW9teJcogF2GR6za6IsvntIoQEAyBBSgJI+BTeBbZawMj4aYp0KzPDrCH9DfhP85tgBUcqAhRNdNiTQmqnSKXJe763YImk4rUJlEgtHwWu5sQGA4W2hym4srsbliN/7bK0KsDzc=
env:
  global:
  - secure: GidoiE6rn6ly5xbEKs59xEDj+KcKsWVSlp7jVJDqIGO78rgzi2Sa3JiiCi/NYp2Q+O1fwUUKQZjRiyKR5RyPlLPVmjdQpdUVqWzmdayQQ0CgQb6y6nN0pPAUZCFJ2p55k1nxFtb5lyFK4hO8E1unElpkLtqPOHb8ANyxpqV+nT96QK7LrvxyqHwY8KmQtwyVFrOUMVWkicCedEszZIQ7U5qE4TNA/zT2PkTrERzSVlhMcDu1aKF3g7a/zjZ4taRZYNoN8BIi/spV9qadBhhZaHER5Jg4Kl7sJAvqIAIXvUhIBguM+PtMI95kRwCVPsmtwjiyrA2GkTTTC3H8XlF6OLZdEXNZiVj/kCy9og79hPf80VKqTEjsHmpe+Vr34LHuIJAYBT2F/CRK0lCdBjmArdIZ+yxI76Clq1uqdJ7zkoz/ffPEFJSPkB3lXJ/r843H7WauKouY59RaL0IXZ3DmqJuDliT2zwWjgDQ2WNkA5JFq2fpwEaaXelGq/07TqGXn/IozcTZyu/tCJKxIsAEupVaDqkACWRVFjt+99ldgBewUpEEikApjXHwUcG2pD9JuEVLtqz4LV7g7ezqSk9O2ta5XU8Yuh9oVEIZBVALtTv8rOkLKRKASmkFl8H32Fo5Bw/5y+GJduWlE0VtJ2U6LC+fsDV/aO+gh+Oj7M57Np4c=
  - secure: q+8oQQqjtuM5YInBWi8L3dp9U9ETG7pAFHKS6NEowRjWEdtof6rMazSUlEwaQj0bYbvNqL3bZgFJvCFwpOuLwEBeHfwDDDhamyuEH6HYf2DlbHhfvNFisIk/6DkTOPwjMs8un8eO0eDBZ//MCy6SmIXHXx4G/Mf53LFRzOJfrtw2kMm7FBji7/911nrOrY2RFl+2lhgyRmGKrd8T9G2rug70VOcMphPsiYoUR/EysrSMbGBbb/JpdNvaCNdl7IOzKp16r7vBNaqQBP3pyhESLV3RiyJaMc1NmYWfNnIhEyQ6ozAGzwti6NmqvANEPSGDVcnSwSItjseXKq+IIwprF6tCH0o7kFIxuOtTPMjkyqYD+dR1Sn5qp0mzpn+mnH/NNeNVIOkItObPyRfrzTFDL1XkjYgFD9DpNGP0Os1eQqHyJzGMrbLycQjuu9bbVJUtxy3vzLZ1J7hrKvZMng4zRDCnpDzeNP0dGp2KHSQovKj6bJvxBLVcpvzL9oTyA22dhtddM9VdnNonEuolfVincRcmgXqiO5qhvpzlbCojEL+SKWspIJc5HwJ9vGlN20KkkHRJGbIEoMASMKaHIaUPWkLMiHOCeuWay02WLseiigGsMun/3EhQAu6nLvb0vGW2IgMAgR+0z6q4DVBmgkRMVmllH+grlH0EjfTz5kENxU4=
